---
abstract: 'An array class of hashes that has magical properties via overloading and AUTOLOAD.'
author:
  - 'Ayhan Ulusoy <dev@ulusoy.name>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: dist/Data-HashArray
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::Dumper: 0
  Scalar::Util: 0
  Test::More: 0
version: 1.02
